//<?php

drupal_set_message("Adding redirects");

$sources = array(
  'content/how-respond-requests-electronic-evidence',
  'content/mssei-guideline-development',
  'content/mssnd-revisions-effective-march-15-2012-0',
  'content/october-campus-data-cleanup-month-lets-shred',
  'SANStraining/index.html',
  'content/2011-san-francisco-ciso-executive-summit',
  'content/mobile-security',
  'content/bring-your-own-device-byod',
  'content/cispc-campus-information-security-privacy-committee-0',
  'content/2012-endpoint-security',
  'content/privacy-guidance-social-media',
  'content/scoring-strategic-value-security',
  'content/cyber-security-what-you-should-know-stay-safe-online',
  'content/horizon-report-action-emerging-technologies-today-and-tomorrow',
  'content/securing-x-windows',
  'content/how-do-i-view-firewall-rules-symantec-endpoint-protection-sep',
  'content/what-difference-between-vulnerability-scan-and-penetration-test',
  'content/what-know-about-mac-os-x-105-end-life-advisory',
  'content/records-management-same-information-management',
  'content/phishing-faqs',
  'content/browser-security-guidelines',
  'content/how-do-i-keep-mozilla-firefox-date',
  'content/how-do-i-keep-google-chrome-date',
  'content/netreg-faq',
  'content/testing',
  'content/mssnd-1-software-patch-update-honeypot-guidelines',
  'content/phishing-scams-ongoing-threat-campus',
  'content/web-browsers-july-2013',
  'content/new-sophisticated-phishing-emails-targeting-css-it-users',
  'content/critical-vulnerabilities-found-apache-struts-patch-immediately',
  'content/critical-microsoft-windows-out-band-security-vulnerability-ms14-068',
  'content/october-campus-data-cleanup-month',
  'content/sans-ouch-oct-2011',
  'content/more-security-updates-google-chrome',
  'content/campus-data-cleanup-winner-announced',
  'content/campus-adds-new-information-security-personnel',
  'content/sans-ouch-dec-2011',
  'content/microsoft-patch-tuesday-dec-2011',
  'content/out-band-microsoft-security-bulletin-ms11-100',
  'content/critical-security-updates-january-2012',
  'content/sans-ouch-jan-2012',
  'content/white-house-releases-consumer-privacy-bill-rights',
  'content/california-secures-global-agreement-strengthen-privacy-protections-users-mobile-applications',
  'content/ftc-and-epic-fight-over-google-privacy-policy',
  'content/sans-ouch-march-2012',
  'content/2013-information-security-awareness-student-video-poster-contest',
  'content/critical-adobe-zero-day-vulnerabilities-and-software-updates',
  'content/malware-targeting-web-browsers',
  'content/critical-internet-explorer-vulnerability-all-versions-affected',
  'content/disable-chargen-service-your-hosts',
  'content/critical-flash-vulnerability-announced-patch-immediately',
  'content/mac-os-x-leopard-version-105-end-support',
  'content/data-privacy-month-free-book-download',
  'content/zero-day-vulnerability-ie',
  'content/critical-network-time-protocol-vulnerabilities',
  'content/security-updates-available-adobe-flash-player',
  'content/standards-development',
  'content/basicpage',
  'content/cispc-campus-information-security-privacy-committee',
  'content/test-alt-img-tag',
  'content/cispc-august-15-2013',
  'content/netreg-1',
  'content/mssei-security-plan-instruction',
  'content/submitting-mssei-self-assessment-plan',
  'content/test-0',
  'content/draft-accessing-requirements',
  'phishing-old',
  'content/are-your-email-communications-phishy',
  'content/error',
  'content/appendix-b',
  'content/test',
  'content/presentations',
  'content/white-papers',
  'content/white-papers-0',
  'content/presentations-0',
  'content/security-groups',
  'content/industry-standards',
  'content/presentations-1',
  'content/access-consent-and-non-consentual-access-forms',
  'content/data-classification-pdf',
  'content/security-contact-orientation',
  'policy/socialmedia',
  'content/security-privacy-training-it-staff',
  'content/data-security-review',
  'content/risk-identification-new-projects',
  'content/dont-get-phished',
  'content/start-mssei-compliance-efforts-now',
  'content/mssei-guidelines-update',
  'content/draft-mssei-2013-give-your-input',
  'content/mssei-guidelines-completed',
  'content/critical-gnu-bash-remote-code-execution-vulnerability-discovered',
  'content/adobe-zero-day-vulnerabilities-and-software-updates',
  'content/spot-the-phish',
  'content/phishing-campaign-results',
  'content/java-security-guidelines-campus',
  'content/zero-day-vulnerability-all-versions-ie',
  'content/zero-day-vulnerability-all-versions-ie-1',
  'content/protection-profile-level-1-moderate-impact-data-draft',
  'content/data-protection-profile-matrix',
  'content/matrix-test',
  'content/draft-information-security-control-catalog',
  'content/annual-registration-information-security-control-1',
  'content/managed-software-inventory-information-security-control-2',
  'content/template-information-security-control-catalog-x',
  'content/malware-defenses-security-control-5',
  'content/controlled-use-administrative-privileges-information-security-control-10',
  'content/application-software-security-security-control-6',
  'content/fair-information-practice-principles-fipps-training-course',
  'content/fair-information-practice-principles-fipps-training-course-0',
  'content/fair-information-practice-principles-fipps-training-course-1',
  'content/faqs',
  'policy/contact-it-policy',
  'content/submit-request-policy-or-standard',
  'content/securing-human-developer-registration',
  'Roz-fights-for-IT-Accessibilty',
  'IT-Accessibility-cartoon-transcript',
  'content/passwords-email-epic-fail',
  'content/if-you-didnt-expect-it-reject-it',
  'content/hover-discover',
  'content/check-trash-slash',
  'content/not-sure-if-its-phish',
  'content/zero-day-vulnerability-all-versions-ie-0',
  'reports/2011',
  'content/ibm-appscan-downloads',
  'content/heartbleed-security-vulnerability-update-spotlight',
  'content/preventing-laptop-theft-defense-depth-approach',
  'policy/asd.policy',
  'content/securing-human-developer-awareness-training',
  'content/application-system-development-guidelines',
  'content/password-theft-happens',
  'content/malware-defenses-guideline',
  'content/information-risk-management-program',
  'content/draft-uc-it-accessibility-policy',
  'accessibility',
  'access',
  'content/minimum-security-standards-electronic-information',
  'MinStds',
  'data-questionnaire',
  'datareg',
  'data-reg',
  'notices',
  'policy/admsecpol',
  'node/307',
  'node/339',
  'node/129',
  'node/130',
  'node/93',
  'node/194',
  ' /node/343',
  'node/246',
  'node/166',
  'node/178',
  'node/183',
  'node/189',
  'node/190',
  'node/210',
  'node/292',
  'node/305',
  'node/352',
  'node/389',
  'node/288',
  'node/373',
  'node/482',
  'node/441',
  'node/51',
  'node/52',
  'node/54',
  'node/55',
  'node/66',
  'node/365',
  'node/77',
  'node/195',
  'node/208',
  'node/252',
  'node/279',
  'node/356',
  'node/375',
  'node/437',
  'node/438',
  'node/439',
  'node/511',
  'node/299',
  'node/426',
  'node/108',
  'node/179',
  'node/312',
  'node/315',
  'node/357',
  'node/444',
  'node/458',
  'node/459',
  'node/575',
  'node/14',
  'node/15',
  'node/70',
  'node/71',
  'node/116',
  'node/136',
  'node/137',
  'node/144',
  'node/169',
  'node/171',
  'node/172',
  'node/173',
  'node/182',
  'node/186',
  'node/188',
  'node/191',
  'node/192',
  'node/198',
  'node/211',
  'node/212',
  'node/242',
  'node/244',
  'node/256',
  'node/257',
  'node/270',
  'node/271',
  'node/272',
  'node/273',
  'node/278',
  'node/281',
  'node/283',
  'node/287',
  'node/316',
  'node/344',
  'node/348',
  'node/349',
  'node/350',
  'node/360',
  'node/422',
  'node/442',
  'node/468',
  'node/478',
  'node/485',
  'node/207',
  'node/219',
  'node/503',
  'node/580',
  'node/589',
  'node/6',
  'node/113',
  'node/199',
  'node/464',
  'node/7',
  'node/64',
  'node/65',
  'node/185',
  'node/452',
  'node/461',
  'node/487',
  'node/492',
  'node/500',
  'node/537',
  'node/538',
  'node/565',
  'node/566',
  'node/536',
  'node/16',
  'node/17',
  'node/18',
  'node/19',
  'node/41',
  'node/42',
  'node/92',
  'node/114',
  'node/128',
  'node/135',
  'node/168',
  'node/362',
  'node/184',
  'node/202',
  'node/203',
  'node/204',
  'node/205',
  'node/206',
  'node/243',
  'node/276',
  'node/297',
  'node/443',
  'node/63',
  'node/174',
  'node/29',
  'node/30',
  'node/82',
  'node/83',
  'node/89',
  'node/177',
  'node/181',
  'node/180',
  'node/340',
  'node/383',
  'node/420',
  'node/433',
  'node/559',
  'node/31',
  'node/423',
  'node/261',
  'node/32',
  'node/351',
  'node/564',
  'node/583',
  'node/429',
  'node/513',
  'node/515',
  'node/298',
  'node/311',
  'node/364',
  'node/366',
  'node/367',
  'node/368',
  'node/369',
  'node/370',
  'node/371',
  'node/372',
  'node/321',
  'node/322',
  'node/323',
  'node/531',
  'node/36',
  'node/200',
  'node/557',
  'node/450',
  'node/451',
  'node/471',
  'node/472',
  'node/477',
  'node/479',
  'node/480',
  'node/504',
  'node/245',
  'node/547',
  'node/494',
  'node/11',
  'node/247',
  'node/43',
  'node/143',
  'node/556',
  'node/225',
  'node/22',
  'node/466',
  'node/401',
  'node/467',
  'node/446',
  'node/446',
  'node/446',
  'node/456',
  'node/237',
  'node/334',
  'node/334',
  'node/334',
  'node/78',
  'node/38',
  'node/134',
);

$target = 'content-retired';

foreach ($sources as $source) {
  $redirect = new stdClass();
  redirect_object_prepare($redirect);
  $redirect->source = $source;
  $redirect->redirect = $target;
  $redirect->language = LANGUAGE_NONE;
  if (drush_scr_redirect_validate($redirect)) {
    redirect_save($redirect);
  }
}

drupal_set_message("Done adding redirects");

function drush_scr_redirect_validate($redirect) {
  // check that there there are no redirect loops
  if (url($redirect->source) == url($redirect->redirect)) {
    drupal_set_message(t('You are attempting to redirect the page to itself. Source=%source; Target=%target', array(
      '%source' => $redirect->source,
      '%target' => $redirect->redirect
    ), array('langcode' => LANGUAGE_NONE, 'context' => '')), "error");
    return FALSE;
  }

  // Make sure a redirect with the same hash doesn't exist already
  redirect_hash($redirect);
  $result = db_query("select source, redirect from {redirect} where hash = :hash", array(
    ':hash' => $redirect->hash
  ));
  if (count($result->fetchallKeyed)) {
    foreach ($result->fetchAllKeyed() as $source => $redirect) {
      drupal_set_message(t("A redirect of :source --> :redirect already exists.", array(
        ':source' => $source,
        ':redirect' => $redirect
      ), array('langcode' => LANGUAGE_NONE, 'context' => '')), "error");
    }
    return FALSE;
  }

  if ($existing = redirect_load_by_hash($redirect->hash)) {
    if ($redirect->rid != $existing->rid) {
      drupal_set_message(t('The source path %source is already being redirected: Source=%source; Target=%target', array(
          '%source' => $existing->source,
          '%target' => $existing->redirect
        ), array('langcode' => LANGUAGE_NONE, 'context' => '')), "error");
      return FALSE;
    }
  }


  return TRUE;
}